<<<<<<< HEAD
version: "3"

services:
  serveur:
    image: adem06/projet_poo-serveur:latest
=======
version: "3.9"

services:
  serveur:
    build: ./server
>>>>>>> dev
    ports:
      - "5000:5000"

  client:
<<<<<<< HEAD
    image: adem06/projet_poo-client:latest
    stdin_open: true
    tty: true
=======
    build: ./client
    depends_on:
      - serveur
    stdin_open: true
    tty: true
    network_mode: "host"
>>>>>>> dev
