version: "3.9"

services:
  serveur:
    build: ./server
    ports:
      - "5000:5000"

  client:
    build: ./client
    depends_on:
      - serveur
    stdin_open: true
    tty: true
    network_mode: "host"
